name: Unity WebGL CI/CD 🎮

on:
  push:
    branches: [ main ]  
  pull_request:

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
  test:
    name: Run Unity Tests 
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Run Unity tests
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build WebGL ✨
    runs-on: ubuntu-latest
    needs: free-disk-space
    # needs: test we don't put dependency since it may run out of container space when we execute jobs sequently. remove the dependency will let them execute in parallel, and they will control their own container.   
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build WebGL
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          allowDirtyBuild: true
          customImage: unityci/editor:ubuntu-6000.2.2f1-webgl-3

      # Upload artifact (for verification or manual download)
      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL

  deploy:
    name: Deploy to itch.io 
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download the build from previous job
      - name: Download WebGL build
        uses: actions/download-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL

      # Install Butler (itch.io CLI)
      - name: Install Butler CLI
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          butler -V

      # Deploy to itch.io
      - name: Upload to itch.io
        run: |
          butler push build/WebGL "${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME_NAME }}:webgl"
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
